import VueGlobalMethods from "@/config/VueGlobalMethods.js";

import BlocksField from "./BlocksField.vue";
import CheckboxesField from "./CheckboxesField.vue";
import DateField from "./DateField.vue";
import EmailField from "./EmailField.vue";
import FilesField from "./FilesField.vue";
import GapField from "./GapField.vue";
import HeadlineField from "./HeadlineField.vue";
import InfoField from "./InfoField.vue";
import LayoutField from "./LayoutField.vue";
import LineField from "./LineField.vue";
import ListField from "./ListField.vue";
import MultiselectField from "./MultiselectField.vue";
import NumberField from "./NumberField.vue";
import PagesField from "./PagesField.vue";
import PasswordField from "./PasswordField.vue";
import RadioField from "./RadioField.vue";
import RangeField from "./RangeField.vue";
import SelectField from "./SelectField.vue";
import SlugField from "./SlugField.vue";
import StructureField from "./StructureField.vue";
import TagsField from "./TagsField.vue";
import TelField from "./TelField.vue";
import TextField from "./TextField.vue";
import TextareaField from "./TextareaField.vue";
import TimeField from "./TimeField.vue";
import ToggleField from "./ToggleField.vue";
import TogglesField from "./TogglesField.vue";
import UrlField from "./UrlField.vue";
import UsersField from "./UsersField.vue";
import WriterField from "./WriterField.vue";

VueGlobalMethods.component("k-blocks-field", BlocksField);
VueGlobalMethods.component("k-checkboxes-field", CheckboxesField);
VueGlobalMethods.component("k-date-field", DateField);
VueGlobalMethods.component("k-email-field", EmailField);
VueGlobalMethods.component("k-files-field", FilesField);
VueGlobalMethods.component("k-gap-field", GapField);
VueGlobalMethods.component("k-headline-field", HeadlineField);
VueGlobalMethods.component("k-info-field", InfoField);
VueGlobalMethods.component("k-layout-field", LayoutField);
VueGlobalMethods.component("k-line-field", LineField);
VueGlobalMethods.component("k-list-field", ListField);
VueGlobalMethods.component("k-multiselect-field", MultiselectField);
VueGlobalMethods.component("k-number-field", NumberField);
VueGlobalMethods.component("k-pages-field", PagesField);
VueGlobalMethods.component("k-password-field", PasswordField);
VueGlobalMethods.component("k-radio-field", RadioField);
VueGlobalMethods.component("k-range-field", RangeField);
VueGlobalMethods.component("k-select-field", SelectField);
VueGlobalMethods.component("k-slug-field", SlugField);
VueGlobalMethods.component("k-structure-field", StructureField);
VueGlobalMethods.component("k-tags-field", TagsField);
VueGlobalMethods.component("k-text-field", TextField);
VueGlobalMethods.component("k-textarea-field", TextareaField);
VueGlobalMethods.component("k-tel-field", TelField);
VueGlobalMethods.component("k-time-field", TimeField);
VueGlobalMethods.component("k-toggle-field", ToggleField);
VueGlobalMethods.component("k-toggles-field", TogglesField);
VueGlobalMethods.component("k-url-field", UrlField);
VueGlobalMethods.component("k-users-field", UsersField);
VueGlobalMethods.component("k-writer-field", WriterField);
